version: '3' 

services: 
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: liquorice-api
    command: ./docker-entrypoint.dev.sh
    ports: 
      - "7001:7001"
    stdin_open: true 
    tty: true 
    depends_on:
      - redis
    restart: unless-stopped
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - ./api:/usr/src/api
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: liquorice-frontend
    command: ./docker-entrypoint.dev.sh
    ports: 
      - "3000:3000"
    stdin_open: true 
    tty: true 
    volumes:
      - ./frontend:/usr/src/frontend

  redis:
    image: redis:latest
    container_name: liquorice-redis
    ports:
      - 6379:6379
    restart: always
    volumes:
      - liquoricedata:/data

  celery:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: liquorice-celery-worker
    command: celery -A liquorice worker --loglevel=info
    depends_on:
      - redis
      - api
    volumes:
      - ./api:/usr/src/api
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

  celery-beat:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: liquorice-celery-beat
    command: celery -A liquorice beat --loglevel=info
    depends_on:
      - redis
      - api
      - celery
    volumes:
      - ./api:/usr/src/api
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

volumes:
  liquoricedata:  
