# Generated by Django 4.0.6 on 2022-07-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=72)),
                ('tags', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=70)),
                ('created_at', models.DateTimeField()),
                ('host', models.CharField(max_length=255)),
            ],
        ),
    ]
