"""database update

Revision ID: 227f971c07bf
Revises: 4e53b1552720
Create Date: 2023-03-12 18:26:38.186976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227f971c07bf'
down_revision = '4e53b1552720'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'environments', ['platform_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'environments', type_='unique')
    # ### end Alembic commands ###
