"""database creation

Revision ID: 298167c544b3
Revises: 
Create Date: 2023-03-11 16:38:24.392714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '298167c544b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_created_at'), 'platform', ['created_at'], unique=False)
    op.create_index(op.f('ix_platform_description'), 'platform', ['description'], unique=False)
    op.create_index(op.f('ix_platform_id'), 'platform', ['id'], unique=False)
    op.create_index(op.f('ix_platform_name'), 'platform', ['name'], unique=True)
    op.create_index(op.f('ix_platform_type'), 'platform', ['type'], unique=False)
    op.create_table('environment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environment_created_at'), 'environment', ['created_at'], unique=False)
    op.create_index(op.f('ix_environment_description'), 'environment', ['description'], unique=False)
    op.create_index(op.f('ix_environment_id'), 'environment', ['id'], unique=False)
    op.create_index(op.f('ix_environment_name'), 'environment', ['name'], unique=True)
    op.create_table('node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('node_ip', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_created_at'), 'node', ['created_at'], unique=False)
    op.create_index(op.f('ix_node_description'), 'node', ['description'], unique=False)
    op.create_index(op.f('ix_node_id'), 'node', ['id'], unique=False)
    op.create_index(op.f('ix_node_name'), 'node', ['name'], unique=True)
    op.create_index(op.f('ix_node_node_ip'), 'node', ['node_ip'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_node_ip'), table_name='node')
    op.drop_index(op.f('ix_node_name'), table_name='node')
    op.drop_index(op.f('ix_node_id'), table_name='node')
    op.drop_index(op.f('ix_node_description'), table_name='node')
    op.drop_index(op.f('ix_node_created_at'), table_name='node')
    op.drop_table('node')
    op.drop_index(op.f('ix_environment_name'), table_name='environment')
    op.drop_index(op.f('ix_environment_id'), table_name='environment')
    op.drop_index(op.f('ix_environment_description'), table_name='environment')
    op.drop_index(op.f('ix_environment_created_at'), table_name='environment')
    op.drop_table('environment')
    op.drop_index(op.f('ix_platform_type'), table_name='platform')
    op.drop_index(op.f('ix_platform_name'), table_name='platform')
    op.drop_index(op.f('ix_platform_id'), table_name='platform')
    op.drop_index(op.f('ix_platform_description'), table_name='platform')
    op.drop_index(op.f('ix_platform_created_at'), table_name='platform')
    op.drop_table('platform')
    # ### end Alembic commands ###
