"""update

Revision ID: 44861d2a9c87
Revises: d8c459b99701
Create Date: 2023-05-12 20:40:22.650601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44861d2a9c87'
down_revision = 'd8c459b99701'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snapshots', sa.Column('snapshot', sa.JSON(), nullable=True))
    op.drop_column('snapshots', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snapshots', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('snapshots', 'snapshot')
    # ### end Alembic commands ###
