"""database update

Revision ID: 4e53b1552720
Revises: 79d66f794c0d
Create Date: 2023-03-12 17:48:13.276137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e53b1552720'
down_revision = '79d66f794c0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('environments', 'platform_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('environments', 'platform_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
