"""update

Revision ID: 52a65f5a14c0
Revises: 
Create Date: 2023-05-10 11:30:52.142067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a65f5a14c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('server_ipv4', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_created_at'), 'nodes', ['created_at'], unique=False)
    op.create_index(op.f('ix_nodes_description'), 'nodes', ['description'], unique=False)
    op.create_index(op.f('ix_nodes_id'), 'nodes', ['id'], unique=False)
    op.create_index(op.f('ix_nodes_name'), 'nodes', ['name'], unique=False)
    op.create_index(op.f('ix_nodes_server_ipv4'), 'nodes', ['server_ipv4'], unique=False)
    op.create_table('platforms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platforms_created_at'), 'platforms', ['created_at'], unique=False)
    op.create_index(op.f('ix_platforms_description'), 'platforms', ['description'], unique=False)
    op.create_index(op.f('ix_platforms_id'), 'platforms', ['id'], unique=False)
    op.create_index(op.f('ix_platforms_name'), 'platforms', ['name'], unique=True)
    op.create_index(op.f('ix_platforms_type'), 'platforms', ['type'], unique=False)
    op.create_table('clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('platform_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['platform_name'], ['platforms.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clusters_created_at'), 'clusters', ['created_at'], unique=False)
    op.create_index(op.f('ix_clusters_description'), 'clusters', ['description'], unique=False)
    op.create_index(op.f('ix_clusters_id'), 'clusters', ['id'], unique=False)
    op.create_index(op.f('ix_clusters_name'), 'clusters', ['name'], unique=False)
    op.create_table('platform_nodes',
    sa.Column('platform_name', sa.String(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['platform_name'], ['platforms.name'], ),
    sa.PrimaryKeyConstraint('platform_name', 'node_id')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('platform_name', sa.String(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_name'], ['platforms.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_created_at'), 'snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_snapshots_id'), 'snapshots', ['id'], unique=False)
    op.create_table('cluster_nodes',
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('cluster_id', 'node_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cluster_nodes')
    op.drop_index(op.f('ix_snapshots_id'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_created_at'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_table('platform_nodes')
    op.drop_index(op.f('ix_clusters_name'), table_name='clusters')
    op.drop_index(op.f('ix_clusters_id'), table_name='clusters')
    op.drop_index(op.f('ix_clusters_description'), table_name='clusters')
    op.drop_index(op.f('ix_clusters_created_at'), table_name='clusters')
    op.drop_table('clusters')
    op.drop_index(op.f('ix_platforms_type'), table_name='platforms')
    op.drop_index(op.f('ix_platforms_name'), table_name='platforms')
    op.drop_index(op.f('ix_platforms_id'), table_name='platforms')
    op.drop_index(op.f('ix_platforms_description'), table_name='platforms')
    op.drop_index(op.f('ix_platforms_created_at'), table_name='platforms')
    op.drop_table('platforms')
    op.drop_index(op.f('ix_nodes_server_ipv4'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_name'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_id'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_description'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_created_at'), table_name='nodes')
    op.drop_table('nodes')
    # ### end Alembic commands ###
