"""update

Revision ID: 6f4a29b95b1d
Revises: bbe483893d49
Create Date: 2023-05-13 23:13:33.321543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f4a29b95b1d'
down_revision = 'bbe483893d49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nodes_name', table_name='nodes')
    op.create_index(op.f('ix_nodes_name'), 'nodes', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nodes_name'), table_name='nodes')
    op.create_index('ix_nodes_name', 'nodes', ['name'], unique=False)
    # ### end Alembic commands ###
