"""database update

Revision ID: 83d3f5a4a06c
Revises: 87c5e2d589ef
Create Date: 2023-03-11 21:24:27.461887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83d3f5a4a06c'
down_revision = '87c5e2d589ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_node_node_ip', table_name='node')
    op.create_index(op.f('ix_node_node_ip'), 'node', ['node_ip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_node_ip'), table_name='node')
    op.create_index('ix_node_node_ip', 'node', ['node_ip'], unique=False)
    # ### end Alembic commands ###
