"""database update

Revision ID: 87c5e2d589ef
Revises: bae6865cdaca
Create Date: 2023-03-11 21:05:06.130995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87c5e2d589ef'
down_revision = 'bae6865cdaca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_platform_name', table_name='platform')
    op.create_index(op.f('ix_platform_name'), 'platform', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_name'), table_name='platform')
    op.create_index('ix_platform_name', 'platform', ['name'], unique=False)
    # ### end Alembic commands ###
