"""update

Revision ID: d8c459b99701
Revises: 52a65f5a14c0
Create Date: 2023-05-10 12:08:15.451388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c459b99701'
down_revision = '52a65f5a14c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster_nodes', sa.Column('id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_cluster_nodes_id'), 'cluster_nodes', ['id'], unique=False)
    op.add_column('platform_nodes', sa.Column('id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_platform_nodes_id'), 'platform_nodes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_nodes_id'), table_name='platform_nodes')
    op.drop_column('platform_nodes', 'id')
    op.drop_index(op.f('ix_cluster_nodes_id'), table_name='cluster_nodes')
    op.drop_column('cluster_nodes', 'id')
    # ### end Alembic commands ###
