import pathlib

import trafaret as t

from config.utils import load_config


BASE_DIR = pathlib.Path(__file__).parent

CONFIG_TRAFARET = t.Dict(
    {
        'AGENT_HOST': t.String,
        'AGENT_PORT': t.Int,
        'DOCKER_CONTAINER': t.String,
        'DOCKER_CONTAINER_START': t.String,
        'DOCKER_CONTAINER_STOP': t.String,
        'DOCKER_CONTAINER_RESTART': t.String,
        'DOCKER_CONTAINER_PAUSE': t.String,
        'DOCKER_CONTAINER_UNPAUSE': t.String,
        'DOCKER_CONTAINER_KILL': t.String,
        'DOCKER_CONTAINER_PRUNE': t.String,
        'DOCKER_CONTAINER_LOGS': t.String,
        'DOCKER_CONTAINER_STATS': t.String,
        'DOCKER_CONTAINER_RUN': t.String,
    }
)


CONF = load_config(
    file=BASE_DIR / 'configs' / 'agent_config.yml',
    config_trafaret=CONFIG_TRAFARET
)


AGENT_HOST = CONF['AGENT_HOST']
AGENT_PORT = CONF['AGENT_PORT']

AGENT_URL = f'http://{AGENT_HOST}:{AGENT_PORT}'

DOCKER_CONTAINER = CONF['DOCKER_CONTAINER']

DOCKER_CONTAINER_START = CONF['DOCKER_CONTAINER_START']
DOCKER_CONTAINER_STOP = CONF['DOCKER_CONTAINER_STOP']
DOCKER_CONTAINER_RESTART = CONF['DOCKER_CONTAINER_RESTART']
DOCKER_CONTAINER_PAUSE = CONF['DOCKER_CONTAINER_PAUSE']
DOCKER_CONTAINER_UNPAUSE = CONF['DOCKER_CONTAINER_UNPAUSE']
DOCKER_CONTAINER_KILL = CONF['DOCKER_CONTAINER_KILL']

DOCKER_CONTAINER_LOGS = CONF['DOCKER_CONTAINER_LOGS']
DOCKER_CONTAINER_STATS = CONF['DOCKER_CONTAINER_STATS']

DOCKER_CONTAINER_PRUNE = CONF['DOCKER_CONTAINER_PRUNE']
DOCKER_CONTAINER_RUN = CONF['DOCKER_CONTAINER_RUN']
