AGENT_HOST: 'localhost'
AGENT_PORT: 8080

DOCKER_CONTAINER: 'docker/containers'

DOCKER_CONTAINER_START: 'start'
DOCKER_CONTAINER_STOP: 'stop'
DOCKER_CONTAINER_RESTART: 'restart'
DOCKER_CONTAINER_PAUSE: 'pause'
DOCKER_CONTAINER_UNPAUSE: 'unpause'
DOCKER_CONTAINER_KILL: 'kill'
DOCKER_CONTAINER_PRUNE: 'prune'
DOCKER_CONTAINER_LOGS: 'logs'
DOCKER_CONTAINER_STATS: 'stats'
DOCKER_CONTAINER_RUN: 'run'

DOCKER_IMAGE: 'docker/images'

DOCKER_IMAGE_PRUNE: 'prune'
DOCKER_IMAGE_BUILD: 'build'
DOCKER_IMAGE_PULL: 'pull'
DOCKER_IMAGE_TAG: 'tag'

DOCKER_NETWORK: 'docker/networks'

DOCKER_NETWORK_CREATE: 'create'
DOCKER_NETWORK_PRUNE: 'prune'
DOCKER_NETWORK_CONNECT: 'connect'
DOCKER_NETWORK_DISCONNECT: 'disconnect'

DOCKER_VOLUME: 'docker/volumes'

DOCKER_VOLUME_CREATE: 'create'
DOCKER_VOLUME_PRUNE: 'prune'

DOCKER_PLUGIN: 'docker/plugins'

DOCKER_PLUGIN_INSTALL: 'install'
DOCKER_PLUGIN_ENABLE: 'enable'
DOCKER_PLUGIN_DISABLE: 'disable'

DOCKER_SYSTEM: 'docker/system'

DOCKER_SYSTEM_EVENTS: 'events'
DOCKER_SYSTEM_PRUNE: 'prune'
DOCKER_SYSTEM_AUTH: 'auth'
