AGENT_HOST: 'localhost'
AGENT_PORT: 8080

DOCKER_CONTAINER: 'docker/containers'

DOCKER_CONTAINER_START: 'start'
DOCKER_CONTAINER_STOP: 'stop'
DOCKER_CONTAINER_RESTART: 'restart'
DOCKER_CONTAINER_PAUSE: 'pause'
DOCKER_CONTAINER_UNPAUSE: 'unpause'
DOCKER_CONTAINER_KILL: 'kill'
DOCKER_CONTAINER_PRUNE: 'prune'
DOCKER_CONTAINER_LOGS: 'logs'
DOCKER_CONTAINER_STATS: 'stats'
DOCKER_CONTAINER_RUN: 'run'

DOCKER_IMAGE: 'docker/images'

DOCKER_IMAGE_PRUNE: 'prune'
DOCKER_IMAGE_BUILD: 'build'
DOCKER_IMAGE_PULL: 'pull'
DOCKER_IMAGE_TAG: 'tag'
