KAFKA_HOST: 'localhost'
KAFKA_PORT: 9093

DOCKER_PLATFORM_NAME: 'docker'
SWARM_PLATFORM_NAME: 'swarm'

DOCKER_KAFKA_PARTITIONS: 8
SWARM_KAFKA_PARTITIONS: 8

DB_USER: 'postgres'
DB_PASS: 'postgres'
DB_HOST: 'localhost'
DB_PORT: '5432'
DB_NAME: 'postgres'