FROM python:3.10-alpine
WORKDIR /usr/src/api

RUN pip3 install --upgrade pip 
COPY requirements.txt .
RUN pip3 install -r requirements.txt

COPY . .

# RUN ["chmod", "+x", "docker-entrypoint.dev.sh"]
# ENTRYPOINT ["./docker-entrypoint.dev.sh"]
